### PR TITLE
Update copy around why there are no Train to Teach events 

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-3461](https://trello.com/c/yyc0z0ke/3461-explain-why-there-are-no-train-to-teach-events-on-the-site-at-present)

### Context

We want to add a note to the about TTT events page explaining why there are currently no Train to Teach events available. Only show the note when there are no TTT events active in the system.

When filtering by Train to Teach events if there are no results we want to show a specific message explaining why that is and when TTT events will start up again.

### Changes proposed in this pull request

- Add message explaining no TTT events to about page
- Add specific no results message when filtering by TTT events

### Guidance to review

| Search Result Desktop      | Search Result Mobile | About Desktop | About Mobile |
| ----------- | ----------- | ----------- | ----------- |
| Screenshot 2022-08-08 at 11 27 47      | Screenshot 2022-08-08 at 11 28 13       | Screenshot 2022-08-08 at 11 29 28       | Screenshot 2022-08-08 at 11 29 15       |

### CODE REVIEW

**Review by EllieNodder — APPROVED** [review]
Looks good to me @gemmadallmandfe @GDW7 @gazcarr?

**Comment by gazcarr** [comment]
@EllieNodder all looks good to me. Nice work

**Review by misaka — DISMISSED** [review]
Looks good!

**Comment by gemmadallmandfe** [comment]
Design/dev looks good to me - @EllieNodder is just checking copy with the Events team as I don't think it is quite right for the changes being made for the Autumn programme

Happy for this to go into prod as soon as that copy is updated

**Comment by EllieNodder** [comment]
@ethax-ross have updated the copy and now there's a conflict I'm not really sure about. Could you take a look?

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me (without being able to test properly, given there are TTT events in the dev environment!)

**Pull request merged**
