### PR TITLE
Upgrade zendesk chat widget with the new code snippet

### PR DESCRIPTION
**Pull request by plisovin**
### Trello card

[Trello-4847](https://trello.com/c/Qqf05GG1/4847-replace-webchat-widget-with-upgraded-version)

### Context

TPUK have suggested replacing the current Zendesk webchat widget with a later version that is more accessible. The current widget is no longer being maintained by Zendesk.

### CODE REVIEW

**Comment by plisovin** [comment]
Screenshot 2023-08-31 at 12 06 05

**Comment by gemmadallmandfe** [comment]
@StackedPancakez Please could you rebase this and then give it a tech review sometime this week, ahead of go-live on 18/10?

I have tested from a front-end perspective (and will retest after it is rebased) - all looks fine

**Review by StackedPancakez — APPROVED** [review]
Looks fine to me from tech perspective. Have rebased and resolved conflicts.

**Comment by gemmadallmandfe** [comment]
This is now due to go-live on **Thursday 19 October** @StackedPancakez 

Please merge as soon as we have had email confirmation (should be around 7.30am)

**Review by gemmadallmandfe — DISMISSED** [review]
Looks good to me - I have retested after the PR was rebased

**Comment by gemmadallmandfe** [comment]
@StackedPancakez FYI The widget id will be reconfirmed to us today (late Weds) but should not have changed

**Review by StackedPancakez — APPROVED** [review]
LGTM

**Review by gemmadallmandfe — APPROVED** [review]
Happy for this to be merged once we receive the go-ahead

**Pull request merged**
