### PR TITLE
Webchat sourcecode

### PR DESCRIPTION
**Pull request by martyn-w**
### Trello card
[Test webchat widget](https://trello.com/c/C9Mu6qKX/6449-test-webchat-widget)

### Context
Test that the webchat widget runs correctly

### Changes proposed in this pull request
Changes include:
* latest version of chat client (8th October, `index-77d633bb.js`)
* CSP security headers
* caching on chat availability API to reduce client requests
* increase polling interval on chat availability api to reduce client requests
* Environmental variables to configure chat targets

### Guidance to review

Test in multiple browsers, mobiles and tablets

### CODE REVIEW

**Review by spencerldixon — DISMISSED** [review]
LGTM! 👍

**Comment by gemmadallmandfe** [comment]
@martyn-w I've tested using keyboard only and that works well

However, when I tested using VoiceOver on iPhone 11, the chat widget opened successfully but focus remained on the GIT website page, which isn't right?

Also, I think we need to indicate to screen reader users that the chat opens in a new window
We do this elsewhere (eg bank holiday link in Talk to us component) with
image

**Comment by gemmadallmandfe** [comment]
Retested on iPhone11 / iOS 17.6.1 and screen reader focus moves to the chat window when opened now

**Review by spencerldixon — DISMISSED** [review]
LGTM 👍

**Review by spencerldixon — DISMISSED** [review]
LGTM 👍

**Review by spencerldixon — APPROVED** [review]
LGTM 👍

**Pull request merged**
