### PR TITLE
Add warning to top of teaching internships

### PR DESCRIPTION
**Pull request by ethax-ross**
> ⚠️ Not to be merged until 6th June

### Trello card

[Trello-3308](https://trello.com/c/ANvK6cL9/3308-update-internships-page-and-backlinks-for-application-closure)

### Context

Schools are now closing their internship application processes; we should display this message to users as of the 6th June.

### Changes proposed in this pull request

- Add warning to top of teaching internships

### Guidance to review

| Desktop      | Mobile |
| ----------- | ----------- |
| Screenshot 2022-05-30 at 15 58 33      | Screenshot 2022-05-30 at 15 59 03       |

### CODE REVIEW

**Comment by EllieNodder** [comment]
@ethax-ross could we also change the link from GSE to our GSE page /train-to-be-a-teacher/get-school-experience? Thanks!

**Review by peteryates — APPROVED** [review]

**Comment by gemmadallmandfe** [comment]
@ethax-ross Can you have a look at why this is failing a check please?

**Comment by gemmadallmandfe** [comment]
Checking with Candidate Experience - pretty sure more content should be removed (eg How to Apply plus provider details) and other content tweaked slightly.

**Comment by gemmadallmandfe** [comment]
@EllieNodder This looks good to me - makes more sense now :-) Do you want to ask Andy H to have a look so we can get this live?

@peteryates there is also still an issue with a failing check - could you have a look please?

**Comment by peteryates** [comment]
Not sure why the 'prevent merges' step is failing. Review apps are building though so I don't think we should let that get in the way of merging when it's ready.

**Comment by ethax-ross** [comment]
@peteryates its because I had the 'do not merge' label on (to prevent it being merged early); I've removed it now

**Comment by gemmadallmandfe** [comment]
@EllieNodder I'm happy with this if Andy is - would be great to get this deployed tomorrow (Thurs)

The only minor comment is the wide gap above the adviser promo? Is it possible to reduce this?

**Comment by EllieNodder** [comment]
> @EllieNodder I'm happy with this if Andy is - would be great to get this deployed tomorrow (Thurs)
> 
> The only minor comment is the wide gap above the adviser promo? Is it possible to reduce this?

Have sent the new review app with the promo banner to Andy. @peteryates anything we can do about reducing the gap?

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
