### PR TITLE
Update README with blog post instructions

### PR DESCRIPTION
**Pull request by ethax-ross**
Starts a content README that contains instructions on creating blog posts, specifically around creating suitable thumbnails images.

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Thanks for this @ethax-ross !

I wonder if it is worth starting off a separate readme that relates to content only - ie for editors rather than devs?

We can then build this out with other info as and when

Any thoughts @peteryates ?

**Comment by peteryates** [comment]
This looks sensible to me. Worth cc'ing @emilytraff and @christinehitch in on this - I believe the main change is to add a thumbnail in addition to a regular-sized image.

The instructions definitely make it clear what needs to be in place though.

**Comment by ethax-ross** [comment]
I've moved this into its own markdown document `/doc/content.md` so that we can keep it separate from the main README and maybe expand it with more guides going forward.

**Comment by gemmadallmandfe** [comment]
@ethax-ross Fab - thanks for doing this. Think this makes a lot of sense and we can add more to it over time.

**Review by sfawcett123 — APPROVED** [review]

**Pull request merged**
