### PR TITLE
Still time to apply

### PR DESCRIPTION
**Pull request by GDW7**
### Trello card
https://trello.com/c/7NgTbMtM/3315-consider-still-time-to-apply-messaging-and-page

### Context
Adding a message to let users know that they still have time to apply for teacher training and to direct them to an appropriate next step depending on which page they're on (and where they're likely at in their journey).

### CODE REVIEW

**Comment by GDW7** [comment]
Hi @EllieNodder would you mind taking a look at the banners I've added so far? They're not formatting properly, but not sure if that's the way they're built or if I've done something wrong. Any ideas?

Also, I'm just working through to see if there are any other pages we might want to add the banner to. If any spring to mind would you let me know please?

**Comment by EllieNodder** [comment]
> Hi @EllieNodder would you mind taking a look at the banners I've added so far? They're not formatting properly, but not sure if that's the way they're built or if I've done something wrong. Any ideas?
> 
> Also, I'm just working through to see if there are any other pages we might want to add the banner to. If any spring to mind would you let me know please?

So sometimes we format links exactly how you have done, i.e. [This is a link] (/link-here).

But sometimes that doesn't work and we have to format them differently (I've gone in and changed them now so you should be able to see what this looks like.)

Not entirely sure why or when this happens! (This is why VS Code comes in handy so you can see if the link renders properly straight away).

**Comment by gemmadallmandfe** [comment]
@GDW7 Always worth looking in the content guidance - there is a section on the inset text component that Ross added with guidance on formatting: https://github.com/DFE-Digital/get-into-teaching-app/blob/master/docs/content.md#inset-text

(The content.md does need a bit of an update with recent site changes though - ticket on the backlog which I will ask Ross to do in the next sprint or two)

**Comment by EllieNodder** [comment]
@GDW7 also thinking, would it be worth adding this to the relevant blog posts about applying?

**Comment by gemmadallmandfe** [comment]
Looks good to me - any other pages you can think of @EllieNodder ?

We should make sure we track how many outbound clicks we get on these links (tagged up in GA automatically).

**Comment by GDW7** [comment]
Thanks for reviewing. @EllieNodder adding to blog articles sounds like a good idea. I've done a bit of a search of the blog posts. Think these are the ones that would be most relevant:
https://getintoteaching.education.gov.uk/blog/how-to-apply-for-teacher-training
https://getintoteaching.education.gov.uk/blog/7-things-to-include-in-your-teacher-training-application
https://getintoteaching.education.gov.uk/blog/application-tips-from-a-teacher-training-provider
https://getintoteaching.education.gov.uk/blog/choosing-the-right-teacher-training-course-provider
https://getintoteaching.education.gov.uk/blog/getting-ready-to-apply

Are there any others you're aware of @EllieNodder?

**Comment by EllieNodder** [comment]
> Thanks for reviewing. @EllieNodder adding to blog articles sounds like a good idea. I've done a bit of a search of the blog posts. Think these are the ones that would be most relevant: https://getintoteaching.education.gov.uk/blog/how-to-apply-for-teacher-training https://getintoteaching.education.gov.uk/blog/7-things-to-include-in-your-teacher-training-application https://getintoteaching.education.gov.uk/blog/application-tips-from-a-teacher-training-provider https://getintoteaching.education.gov.uk/blog/choosing-the-right-teacher-training-course-provider https://getintoteaching.education.gov.uk/blog/getting-ready-to-apply
> 
> Are there any others you're aware of @EllieNodder?

Those sound good to me!

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me - happy for one of you to merge this tomorrow (Thursday) @GDW7  @EllieNodder

**Review by EllieNodder — APPROVED** [review]
looks good to me

**Pull request merged**
