### PR TITLE
Enable Google Optimize on homepage

### PR DESCRIPTION
**Pull request by ethax-ross**
We want to run an experiment on the homepage; enable Google Optimize so the script is included.

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
@ethax-ross Can we close this PR now?

**Comment by ethax-ross** [comment]
@gemmadallmandfe Ramone was just asking me about this and it sounded like we're going ahead with the landing home page test, so will we not want this still?

**Comment by gemmadallmandfe** [comment]
@ethax-ross was thinking this was the blur-specific version but of course this PR is just adding Optimize to the page

Yes, we are still going ahead with a home page test (just a different one than before!)

**Comment by ethax-ross** [comment]
Closing this in favour of #3224

**Pull request closed without merging**
