### PR TITLE
Handle when the chat feature is offline

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-1867](https://trello.com/c/nfOh92rd/1867-replace-klick2contact-eckoh-with-zendesk-for-webchat)

### Context

When the chat is unavailable we want to have 'Chat closed.' in the talk to us section. In other places where a chat button is shown we either want to hide the chat button completely (if not referenced by surrounding copy) or replace it with some offline text to inform the user that its unavailable at the moment but will be online between certain days/times.

### Changes proposed in this pull request

- Handle when the chat feature is offline
- Use JS to handle when chat is offline

### Guidance to review

The first attempt (in the first commit) was in Rails and had an issue due to the way we cache the static pages (using etags which change on deployment). To get around the issue where someone sees the incorrect state due to their cache we have to change the button status dynamically in JS (second commit).

Users with JS disabled will still see a button but it links to the talk to us section where we detail the opening hours (and will eventually have an email address for them to use).

| Online      | Offline |
| ----------- | ----------- |
| Screenshot 2021-09-14 at 09 22 56      | Screenshot 2021-09-14 at 09 21 30       |
| Screenshot 2021-09-14 at 09 23 07   | Screenshot 2021-09-14 at 09 21 56        |
| Screenshot 2021-09-14 at 09 25 20   | Screenshot 2021-09-14 at 09 22 25        |
|  Screenshot 2021-09-14 at 09 23 27   | Screenshot 2021-09-14 at 09 22 35        |

### CODE REVIEW

**Review by peteryates — DISMISSED** [review]
This looks fine to me.

Perhaps worth extending to block out predictable bank holidays too, although that can be done later.

**Comment by ethax-ross** [comment]
@gemmadallmandfe I've updated the closed text to remove the full stop and make it bold. I also noticed another place the chat link is used so I've included screenshots of how it looks online/offline if you can check you're happy with that too.

| Footer update      | Eligibility checker (online) | Eligibility checker (offline) |
| ----------- | ----------- |---------------|
| Screenshot 2021-09-16 at 09 02 53      |  Screenshot 2021-09-16 at 09 02 27      | Screenshot 2021-09-16 at 09 02 16    |

**Comment by peteryates** [comment]
unrelated but that purple box shouldn't be overhanging - will fix that 😄

**Review by gemmadallmandfe — APPROVED** [review]
Thanks @ethax-ross - happy to approve on the basis of the screenshots but will test properly out of hours in dev/test.

I have raised a separate ticket to review how we are promoting chat across the site - but this can wait until after the Zendesk go-live.

**Pull request merged**
