### PR TITLE
Remove a non-breaking space from docs

### PR DESCRIPTION
**Pull request by duncanjbrown**
Noticed when working on https://github.com/DFE-Digital/teacher-services-tech-docs/pull/46!

### CODE REVIEW

**Comment by duncanjbrown** [comment]
it looks like opening from a fork might have broken CI?

**Comment by gemmadallmandfe** [comment]
@duncanjbrown Is this PR still needed?

**Comment by duncanjbrown** [comment]
Yes please!

**Review by plisovin — APPROVED** [review]

**Comment by saliceti** [comment]
Recreated here https://github.com/DFE-Digital/get-into-teaching-app/pull/3590 to be able to build the docker image

**Pull request closed without merging**
