### PR TITLE
Update and improve the subject-specific styling

### PR DESCRIPTION
**Pull request by peteryates**
### Trello card

No card, just minor visual tweaks.

### Context

The images on the subject specific page were positioned a bit awkwardly. This is an attempt to improve them.

| Before | After |
| ----- | ----- |
| Screenshot from 2022-03-30 15-11-43 | Screenshot from 2022-03-30 15-11-37 |
| Screenshot from 2022-03-30 15-11-10 | Screenshot from 2022-03-30 15-11-24 |

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Looks better to me @peteryates (although I'm not totally convinced by having a hero image on an angle, especially on mobile?)

but @gazcarr 's view more important here!

NB I have raised a ticket on this for completeness/tracking purposes (https://trello.com/c/x2B9a5ou)

One thing I have realised is that we don't have a breadcrumb on these subject pages. However, I think we can't really address this until the nav work is done - these pages sit under `/subjects/` yet we don't have an overall subjects page that could be accessed from the breadcrumb! I'll raise a ticket for a future sprint on this.

**Comment by peteryates** [comment]
Thanks @gemmadallmandfe 

Here it is without the tilted hero image.

| Desktop | Mobile |
| ----- | ------ |
|  Screenshot from 2022-03-30 18-36-32 | Screenshot from 2022-03-30 18-36-42 |

Happy with either

**Comment by gemmadallmandfe** [comment]
> Thanks @gemmadallmandfe
> 
> Here it is without the tilted hero image.
> 
> Desktop	Mobile
> Screenshot from 2022-03-30 18-36-32	Screenshot from 2022-03-30 18-36-42
> Happy with either

Over to you @gazcarr !

**Comment by gazcarr** [comment]
@peteryates @gemmadallmandfe 

Yes I agree, no angles for the hero pics look good to me.

**Comment by peteryates** [comment]
@gemmadallmandfe @gazcarr - ok, I've removed the tilt. Agree it looks better

**Comment by gemmadallmandfe** [comment]
This looks great - have tested on my iPhone too and really like it on mobile.

I'm presuming that the only pages this affects at the moment are:

* https://review-get-into-teaching-app-2405.london.cloudapps.digital/subjects/maths
* https://review-get-into-teaching-app-2405.london.cloudapps.digital/subjects/engineers-teach-physics

ie it doesn't affect the Welcome pages?

If so, I'm happy to approve this and for it to be merged to prod, if you two agree @peteryates @gazcarr

**Comment by peteryates** [comment]
Yep, it's specific to those two pages @gemmadallmandfe

**Review by gazcarr — APPROVED** [review]

**Pull request merged**
