### PR TITLE
Update GTM service ID for production

### PR DESCRIPTION
**Pull request by ethax-ross**
> :warning: Pending a green light from Shivani

### Trello card

[Trello-1490](https://trello.com/c/1tODW5fa/1490-update-gtm-for-public-beta)

### Context

We are using a new container when going into public beta in order to differentiate the metrics from private beta.

### Changes proposed in this pull request

- Update GTM service ID for production

### CODE REVIEW

**Comment by MylesJarvis** [comment]
@ethax-ross should this be closed? Just seeing it's super out of date now

**Comment by ethax-ross** [comment]
@MylesJarvis this is still relevant but its waiting on Shivani giving a green light, I checked in with her last week and this is still the plan

**Comment by gemmadallmandfe** [comment]
@ethax-ross just checking whether this should be closed now?

**Comment by ethax-ross** [comment]
Shivani confirmed this is no longer needed.

**Pull request closed without merging**
