### PR TITLE
Fix broken iQTS (teaching in Wales)

### PR DESCRIPTION
**Pull request by laurahermionetennant92**
Fix broken iQTS (teaching in Wales)

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
@laurahermionetennant92 Build has failed - I think it is to do with the Get an IRP file (which is empty)

Might be one for @ethax-ross or @plisovin to help you with

**Comment by laurahermionetennant92** [comment]
@plisovin Hi there, could you take a look at @gemmadallmandfe comment above? Empty Get an IRP file (that's another PR I have going)

**Comment by laurahermionetennant92** [comment]
@gemmadallmandfe this is building and ready for you to review – thank you :)

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me - I will merge this tomorrow morning

**Pull request merged**
