### PR TITLE
Updating content following feedback about accuracy

### PR DESCRIPTION
**Pull request by Tomcowan1**
### Trello card

https://trello.com/c/0REY4GDx/1944-review-wording-on-ways-to-train-re-time-spent-on-theory-of-teaching

### Context

Have edited wording. Hopefully speaking to Policy to agree it.

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Changes look good to me @Tomcowan1 - have they been approved by policy?

The only wording I would maybe question is 'These courses are **usually suitable**....' under Earn a salary. I'm presuming it is worded like this as we need to keep it open - ie it is not _mandatory_ to have teaching experience to do this type of training, but it is usual?

**Comment by Tomcowan1** [comment]
> Changes look good to me @Tomcowan1 - have they been approved by policy?
> 
> The only wording I would maybe question is 'These courses are **usually suitable**....' under Earn a salary. I'm presuming it is worded like this as we need to keep it open - ie it is not _mandatory_ to have teaching experience to do this type of training, but it is usual?

@gemmadallmandfe Yes that's right. It's not mandatory, and UCAS currently describe it as "transferable experience", but a TTA has told me before that this way of training is really only open to people who are doing the course as a way to qualify in a job they're already pretty much doing.

**Comment by gemmadallmandfe** [comment]
Thanks @Tomcowan1 - looks good to me but will not approve until you've met with policy :-)

**Comment by Tomcowan1** [comment]
HI @gemmadallmandfe have talked Rick Rahman from the ITT compliance team (who worked with Emma) through the changes and he is happy. Think we're good to merge.

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
