### PR TITLE
Update for cookie pop up for Public Beta

### PR DESCRIPTION
**Pull request by MylesJarvis**
### Trello card
https://trello.com/c/SzZclVs5/1381-update-cookie-policy-in-line-with-the-nhs-other-gov-depts-examples

### CODE REVIEW

**Review by peteryates — APPROVED** [review]
Looks good 🍪

**Comment by peteryates** [comment]
Here's how it looks now:


https://user-images.githubusercontent.com/128088/113858146-4ea39300-979b-11eb-9726-4a303e48e0a2.mp4

| Desktop | Mobile (Chrome) | Mobile (Firefox) |
| ------ | ------- | ------- |
|  Screenshot from 2021-04-07 12-14-59 | Screenshot from 2021-04-07 12-11-35 | Screenshot from 2021-04-07 12-11-20 |

**Review by peteryates — APPROVED** [review]
Looks good.

**Review by MylesJarvis — COMMENTED** [review]
LGTM - but needs an additional review

**Pull request merged**
