### PR TITLE
Update event structured data images

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-3626](https://trello.com/c/BFayNrcz/3626-review-event-structured-data)

### Context

Update the images to match the new Get Into Teaching event images and correct the 4x3 aspect ratio versions.

### Changes proposed in this pull request

- Update event structure data images

### CODE REVIEW

**Comment by ethax-ross** [comment]
@gazcarr the images, mainly that you're happy with how I've cropped them (they need to be certain aspect ratios for structured data images)

**Review by gazcarr — COMMENTED** [review]
The image of the in person event is fine but I actually think the old laptop image is better. Not sure where that one came from?
@gemmadallmandfe is it worth swapping this out on the event page itself as well if we want to use the old laptop image?

**Comment by gemmadallmandfe** [comment]
Let's go with what's in the PR @ethax-ross @gazcarr - the new laptop image (as used in this PR and on the event pages) has also been used elsewhere in the events journey (eg emails)

**Review by gemmadallmandfe — DISMISSED** [review]
Looks good to me

**Comment by gemmadallmandfe** [comment]
@ethax-ross If you need me to approve again once the conflicts have been resolved, let me know!

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
