### PR TITLE
Remove the feedback component from the website

### PR DESCRIPTION
**Pull request by garethwilliamsdesign**
### Trello card

[Trello 5049](https://trello.com/c/fjUSFOIS/5049-remove-the-feedback-component-from-the-website)

### Context

The current feedback component (located just above the footer), is simply a link to the feedback form and is duplicated in the footer. We have decided to remove the component but retain the footer link as this is a more typical location for such a feature.

### Changes proposed in this pull request

Removal of the feedback component across the website.

### Guidance to review

Check for the presence of the feedback component above the footer on various page layouts. If it's visible, further changes will be required.

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
This looks fine to me on the front end @garethwilliamsdesign 

However, would be good to get @plisovin to have a look at it from a tech perspective

@plisovin Should we be setting `feedback` to `false` or should we be removing this altogether? I would have thought the latter but I don't know how the component works!

**Comment by plisovin** [comment]
> This looks fine to me on the front end @garethwilliamsdesign
> 
> However, would be good to get @plisovin to have a look at it from a tech perspective
> 
> @plisovin Should we be setting `feedback` to `false` or should we be removing this altogether? I would have thought the latter but I don't know how the component works!

If it's not gonna be used anymore with the ```feedback`` flag, then we could remove it altogether. But I would do it in a separate PR.

**Comment by gemmadallmandfe** [comment]
Fine with me @plisovin - I'll raise a separate ticket for that

Are you happy with this PR from a tech perspective? If you could approve, that would be great

**Review by plisovin — APPROVED** [review]

**Review by gemmadallmandfe — APPROVED** [review]
Happy for this to be merged - have raised a separate ticket to clean up the code

**Pull request merged**
