### PR TITLE
Integrate the Zendesk Chat widget

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-1867](https://trello.com/c/nfOh92rd/1867-replace-klick2contact-eckoh-with-zendesk-for-webchat)

### Context

We are moving away from using klick2contact as our online chat provider and instead want to integrate the Zendesk Chat widget. Initially, the Zendesk Chat default CTA will be hidden and when a user clicks on one of our 'chat online' buttons we want to open the chat window.

We have a number of places the online chat buttons appear and should look to consolidate the code around them and the behaviour for when JS is disabled (in some cases we hide the button, in other cases we scroll them to the talk to us section and for some we do nothing). We should look to fallback gracefully, ideally by keeping the buttons around and directing the user to the talk to us section so that they can get in touch another way, or by hiding the button if a fallback isn't applicable (such as for the primary button in the talk to us section itself).

### Changes proposed in this pull request

- Include Zendesk Chat JS snippet

Includes the Zendesk Chat JS snippet in the `<head>`. Loading is deferred as it isn't required until after the document has been parsed (it will be triggered by clicking a button on the page).

The chat will initially be available in non-production environments only.

- Move chevron into CSS

The `git-link` hyperlinks have a chevron at the end that is currently a `<span>` with font awesome classes applied. This removes the need for the `<span>` and instead specifies the icon in the `.git-link` CSS class, which means we can use this type of link via the `chat_link` helper more easily.

- Update all chat links to use helper

We were including chat links manually in a number of ways. There was a pre-existing helper to generate a chat link, so this updates all references to use that.

- Open Zendesk Chat widget when enabled

When the `zendesk_chat` config is enabled we want to open the Zendesk Chat widget instead of the current klick2contact window.

- Add fallback support to chat online buttons

We reference the chat online buttons in a number of different places, namely:

```
- In the 'talk to us' section of the footer
- As a card on the funding page
- As a CTA on the steps to become a teacher page
- In a explore section component on the individual story pages
```

When JS is enabled these all work fine, however we need to provide fallback behaviour for when JS is disabled. For most cases we can change the button text slightly and have it take them down the page to the 'talk to us' section, which provides a telephone number and TTA CTA. In other cases, such as within the talk to us section itself, we can simply hide the button.

- Fix issue with Zendesk Chat and Turbolinks

The Zendesk Chat snippet appears to have logic in it to prevent the widget being accidentally loaded on the page multiple times. This prevents it from re-loading on a page change by Turbolinks even when included in the `<body>` tag. To get around this we need to clear `window.zEACLoaded` so that the script re-evaluates.

### Guidance to review

The default chat button in the bottom right of the page is currently visible when it shouldn't be (I've put in a request for them to disable it appearing by default).

The Zendesk Chat widget is only enabled in non-production environments for now.

Examples of each place the chat online button appears and how it looks with/without JS enabled.

| JS Enabled      | JS Disabled | JS Disabled Behaviour |
| ----------- | ----------- |----------- |
| Screenshot 2021-09-10 at 14 24 03     | Screenshot 2021-09-10 at 14 23 48    | Hide when JS disabled (only show telephone)    |
| Screenshot 2021-09-10 at 14 27 09   |  Screenshot 2021-09-10 at 14 25 22        | Change text to 'chat to us' and scroll down to talk to us section on click |
| Screenshot 2021-09-10 at 14 27 57   | Screenshot 2021-09-10 at 14 27 38        | Change text to 'chat to us for qualifications advice' and scroll down to talk to us section on click     |
| Screenshot 2021-09-10 at 14 30 23   | Screenshot 2021-09-10 at 14 29 10        |  Change text to 'chat to us' and scroll down to talk to us section on click       |

### CODE REVIEW

**Review by peteryates — COMMENTED** [review]
Code-wise this looks fine to me, the chat box triggers correctly and looks good.

I'm seeing quite a few JavaScript errors in the console though:

```
TypeError: this.show is not a function
    at e.value (talk-to-us_controller.js:7)
```

And the classic:

```
web-widget-chat-sdk-ad0bca0cd862985f164f.js:2 Refused to connect to 'wss://widget-mediator.zopim.com/s/W/ws/DnCIl+ZESHUepmlq/c/1631287634140' 
```

**Comment by ethax-ross** [comment]
Ah damn more CSP violations, I'll pin those down 😩

**Comment by peteryates** [comment]
All looks great in Chrome. In Firefox I get [this bug](https://user-images.githubusercontent.com/128088/133075850-b34909a0-d563-480c-a0ae-67178121889c.png):

```
TypeError: window.$zopim is undefined
    value talk-to-us_controller.js:17
    value talk-to-us_controller.js:10
    invokeWithEvent binding.js:67
    handleEvent binding.js:40
    handleEvent event_listener.js:41
```

Perhaps a timing issue?

**Review by peteryates — APPROVED** [review]
Looks good and seems to work fine when testing

**Comment by gemmadallmandfe** [comment]
Tested that the widget opened successfully on desktop and on an iPhone 11 as follows:

- 'Talk to us' section of the footer
- Card on the funding page
- As a CTA on the steps to become a teacher page
- Explore section component on the individual story pages

All look fine to me. Happy for this to be merged @ethax-ross with the caveat that:

a) there is some work to be done on the widget config at the Zendesk end re wording/opening hours
b) the work to handle hiding this chat online button out of hours will be done separately

**NB I presume this is not being merged to prod yet and will remain in the dev environment for UAT?**

**Pull request merged**
