### PR TITLE
Create new rake task that utilizes an ERB file to generate the teaching internship providers page and update the documentation

### PR DESCRIPTION
**Pull request by StackedPancakez**
### Trello card
[5122](https://trello.com/c/1yu2FmxL/5122-improve-upload-of-internship-listings)

### Context
Current process of generating new internship listings and updating the page is long, manual, and error prone due to output and formatting of previous rake task. This changes that to use a consistently formatted erb template to inject the internship providers without the need for copy pasting and manual format checking / intervention.

### Changes proposed in this pull request
Use an erb template file paired with a new rake task to generate the teaching-internship-providers.md file.

### Guidance to review
This PR contains the new rake task, the erb template file, but also an updated version of the teaching-internship-providers.md that has been generated using the erb template to ensure it works correctly. So as well as a code review from the tech side, a review of the content and that it is consistent with how it was displaying before on the review apps should be done as well.

### CODE REVIEW

**Review by gemmadallmandfe — DISMISSED** [review]
Looks good to me as far as the front end is concerned!

**Comment by StackedPancakez** [comment]
DO NOT MERGE!

This PR is currently based on top of the changes in [Creating-Is-teaching-right-for-me-category-page](https://github.com/DFE-Digital/get-into-teaching-app/tree/Creating-Is-teaching-right-for-me-category-page). This is because it requires changes made to it based on work and changes made in that branch.

After the merge of that branch, this will be rebased on top of master and the PR base pointing to master, after which it will once again be ready for merging.

**Review by gemmadallmandfe — APPROVED** [review]
Front-end looks good to me - happy for this to be merged once it has had tech eyes on it

**Comment by StackedPancakez** [comment]
> 👍 I've approved, but a comment for your perusal.
> 
> I know this rake task is not part of the run time website, but could we have some very simplistic rspecs to test an input CSV file (Say just 3 entries), and then test the corresponding output erb file is as expected.
> 
> This comment is optional and I'll leave to your discretion.

@asatwal 
I will add those tests before merge, thanks for picking that up and raising it! 👍

**Pull request merged**
