### PR TITLE
adding meta description and keywords

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card
https://trello.com/c/YmLl4Y1D

### Context

Noticed that the maths page doesn't currently have a meta description or keywords tags. Thought I'd quickly open up a PR to add these in.

### CODE REVIEW

**Comment by EllieNodder** [comment]
@ethax-ross do we know why this is failing? :(

**Comment by ethax-ross** [comment]
@EllieNodder the CI had got into a funny state, I've fixed it now. Ping me on Slack or Trello if I miss the GitHub mentions btw I tend not to get email notifications for GitHub as its all or nothing and gets quite noisy 😬

**Comment by EllieNodder** [comment]
@gemmadallmandfe @GDW7 when working on the ETA page, noticed our maths page doesn't currently have a meta description or keywords in the frontmatter. Thought I'd open up a quick PR to add these in (unless there was a reason we left these out or I'm missing something!)

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me (good spot!)

**Pull request merged**
