### PR TITLE
Add manchester university Find link

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card

https://trello.com/c/IzaeQfYr/2958-new-content-for-engineers-teach-physics-itt

### CODE REVIEW

**Comment by EllieNodder** [comment]
Merging on hold until Manchester give final approval.

**Comment by gemmadallmandfe** [comment]
Looks good to me (when Manchester are ready!)

**Comment by valentine-carter** [comment]
Looks good to me too, ready to go when it's time to shine finally arrives.

**Review by gemmadallmandfe — APPROVED** [review]
Manchester have now approved so this can be published

**Pull request merged**
