### PR TITLE
Updating-funding-your-training-scholarships-and-bursaries-section

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card

https://trello.com/c/nyElIEI9/2935-update-links-to-2022-23-funding-guidance-on-govuk

https://trello.com/c/5H2yZnJj/2951-clarify-wording-around-scholarships

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Changes read so much better to me @EllieNodder! I'm tagging in @valentine-carter for info

I'd suggest we mark this with a policy label and say that it has been seen by policy?

I'd also suggest we show the changes to the Funding team and the High Potential team who flagged the changes originally (details on Trello) before they are merged?

**Comment by gemmadallmandfe** [comment]
Waiting for a reply from the Funding and HPITT teams before this is merged - @EllieNodder emailed them last week

**Comment by EllieNodder** [comment]
Funding and HPITT teams are happy with the changes.

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
