### PR TITLE
Updating events promo

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card

https://trello.com/c/TZ3OU9BW/3270-update-event-promo-module-to-promote-london-train-to-teach-event

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Thanks for doing this so quickly!

Need to update the link as well:
`/events/train-to-teach-london-event-110622`

**Comment by EllieNodder** [comment]
> Thanks for doing this so quickly!
> 
> Need to update the link as well: `/events/train-to-teach-london-event-110622`

oops , yeah 😂 will do

**Comment by EllieNodder** [comment]
@peteryates not quite sure why I'm getting a 404 when I try and click on the London event in the promo on the bottom of the 'if you have a degree' page? 🤔

**Comment by gemmadallmandfe** [comment]
> @peteryates not quite sure why I'm getting a 404 when I try and click on the London event in the promo on the bottom of the 'if you have a degree' page? 🤔

because we don't have these events set up in the dev environment - it's fine!

**Review by peteryates — APPROVED** [review]
Looks good, [full link works on live](https://getintoteaching.education.gov.uk/events/train-to-teach-london-event-110622).

**Pull request merged**
