### PR TITLE
Create a career prospects page

### PR DESCRIPTION
**Pull request by garethwilliamsdesign**
### Trello card

[Trello 5093](https://trello.com/c/zRoSpKU4)

### Context

Users have told us in research that they would expect to read more about the career prospects for teaching at an early stage in considering it as a career.

### Changes proposed in this pull request

Develop a career progression page to explain the possible job progression of a career in teaching.

### Guidance to review

It's done when:

- we have reviewed the research and identified what users expect from this content
- we have agreed a draft of the content
- we have developed the page in GitHub
- we have published the page

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
@garethwilliamsdesign @MaxineCl Can we close this PR now we have decided not to use the accordion component?

**Comment by garethwilliamsdesign** [comment]
> @garethwilliamsdesign @MaxineCl Can we close this PR now we have decided not to use the accordion component?

I'm happy for it to be binned, but, as an alternative, I could simply remove the accordion and leave a blank page ready for @MaxineCl to add content to?

**Comment by MaxineCl** [comment]
@garethwilliamsdesign @gemmadallmandfe I don't mind. If it's easier to leave a blank page we can do that and I can drop the new content in once it's approved. Whatever works best for you guys.

**Comment by gemmadallmandfe** [comment]
OK - I'm going to close this to clear down our PRs before the code freeze as the effort of either option is not much different.

Thanks both!

**Pull request closed without merging**
