### PR TITLE
Amending name and contact details

### PR DESCRIPTION
**Pull request by Tomcowan1**
Change to details requested by Rick in the Market Regulation Team. Original request came from the Pilgrim Partnership.

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Change looks fine to me @Tomcowan1 👍 

However, the build has failed one check (not sure why) so haven't approved - one to check with @peteryates !

NB might be worth asking the Accreditation team whether the provider wants their website adding which I presume is https://pilgrimpartnership.org/ - but that can be done later!

**Comment by Tomcowan1** [comment]
Thanks @gemmadallmandfe have messages Pete about the fail - will pick up tomorrow. Good point about the web address.

**Comment by peteryates** [comment]
This is just down to a flaky build @Tomcowan1 -  retried it and it seemed to work!

**Comment by Tomcowan1** [comment]
Thanks @peteryates I think this is good to go when you're ready @gemmadallmandfe 

I've spoken to Support who will ask if there's a web address. If so, I'll add in a separate PR.

**Review by gemmadallmandfe — APPROVED** [review]
Happy for this to be merged

If/when you add the website address @Tomcowan1 we should sort out the alphabetical ordering!

**Pull request merged**
