### PR TITLE
Updating hint text about QTS on adviser funnel

### PR DESCRIPTION
**Pull request by philspray**
### Trello card

https://trello.com/c/qoNEpEcT

### Context

We need to change the link currently pointing users to apply for QTS in advance of the next IRP announcement on Monday.

### Changes proposed in this pull request

- Updated text and link

### CODE REVIEW

**Comment by tejasjinaraldfe** [comment]
@philspray _If you **are** qualified as a teacher outside the UK, you may be able to [apply for QTS].
'are' missing in copy of the text.

**Comment by tejasjinaraldfe** [comment]
As discussed previously, happy to approve either of the versions. @philspray please merge the changes.

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me (and approving on @tejasjinaraldfe's behalf!)

**Review by EllieNodder — APPROVED** [review]
lgtm 👍🏻

**Pull request merged**
