### PR TITLE
Begin adding story page content to welcome guide

### PR DESCRIPTION
**Pull request by peteryates**
### Trello card

https://trello.com/c/Sf5OA4RC/1742-welcome-guide-story-pages

### Context and changes

Begin adding sample story content from the designs.

#### Progress so far

| My journey into teaching | Bringing your lessons to life |
| ---------------- | ------------------- |
| Screenshot from 2021-07-26 15-54-42 | Screenshot from 2021-07-26 15-54-51 |

### CODE REVIEW

**Comment by peteryates** [comment]
Now with a 'Three things you'll never hear me say' section.

| Desktop | Mobile | 
| ------- | -------- |
| Screenshot from 2021-07-27 11-58-52 | Screenshot from 2021-07-27 11-59-03 |

**Comment by peteryates** [comment]
I missed the custom emphasis style in the 'three things' bit, added in the last commit.

Screenshot from 2021-07-27 12-16-55

**Comment by peteryates** [comment]
Also here are my grid layouts for future reference 📐 

Screenshot from 2021-07-27 12-18-27

**Comment by peteryates** [comment]
Special shout out 📣 

Screenshot from 2021-07-27 16-23-51

**Comment by peteryates** [comment]
Now with links from the `/welcome` page

| Desktop | Mobile |
| ----- | ------ |
| Screenshot from 2021-07-28 15-41-20 | Screenshot from 2021-07-28 15-40-51 |

**Review by MylesJarvis — APPROVED** [review]

**Pull request merged**
