### PR TITLE
Changing meta description to boost CTR

### PR DESCRIPTION
**Pull request by Tomcowan1**
Trello card: https://trello.com/c/2CruTKgi/1743-content-review-meta-descriptions-for-pages

Editing meta descriptions to increase click through rates.

### CODE REVIEW

**Review by peteryates — APPROVED** [review]
Looks good

**Comment by peteryates** [comment]
@Tomcowan1 - I've rebased this, ready to merge once approved

**Review by MylesJarvis — APPROVED** [review]

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me!

**Review by peteryates — APPROVED** [review]
These all look good to me.

**Pull request merged**
