### PR TITLE
Remove unused nav-cards partials

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-3452](https://trello.com/c/jomu3l6g/3452-look-at-nav-card-descriptions?filter=member:rossoliver15)

### Context

It looks like these partials were a prototype for the category cards. They have since been replaced by the `category` layout and content in frontmatter.

### Changes proposed in this pull request

- Remove unused nav-cards partials

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Looks good to me but will leave to @EllieNodder to approve as she knows more about this than I do!

@ethax-ross will the content.md need updating or is this OK?

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me if @EllieNodder is happy with it

I've tested the title change - all OK

**Review by EllieNodder — APPROVED** [review]
Looks good to me (also piggybacked onto this PR to change the title of one of the cards)

**Comment by EllieNodder** [comment]
@ethax-ross do we need Misha to have a look over this before we merge?

**Comment by ethax-ross** [comment]
@EllieNodder its just content thats changed so happy to merge this one now you've approved.

**Pull request merged**
