### PR TITLE
Editing if you do not have a degree content

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card

https://trello.com/c/z7JgL2VM/3831-make-it-more-explicit-you-need-a-degree-to-train-on-if-you-dont-have-a-degree

### Context

UR found that we aren't being clear enough on our if you do not have a degree page that you need a degree to teach primary and secondary.

### CODE REVIEW

**Comment by EllieNodder** [comment]
Awaiting sign off from policy

**Comment by gemmadallmandfe** [comment]
Looks good to me @EllieNodder - happy to approve/merge once policy have seen this

**Review by philspray — COMMENTED** [review]
Looks good to me

**Comment by EllieNodder** [comment]
Signed off by policy (Gaby) - ready to merge @gemmadallmandfe

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
