### PR TITLE
Make completed wizard step headings h1 tags

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-3241](https://trello.com/c/148ske6v/3241-dac-audit-missing-main-heading)

### Context

DAC have raised this; as there are no other headings on the page we should promote these to be `h1` tags.

### Changes proposed in this pull request

- Make completed wizard step headings h1 tags

- Correct document heading structure

As the completed page heading is how a `h1` tag (albeit styled like a `h2` tag) the subsequent headings should be `h2` tags (styled as `h3` tags!).

We need to look at the headings more widely to standardise some of this further.

### Guidance to review

Relevant pages: [mailing list completed](https://review-get-into-teaching-app-2533.london.cloudapps.digital/mailinglist/signup/completed) [callback completed](https://review-get-into-teaching-app-2533.london.cloudapps.digital/callbacks/book/completed) [event completed](https://review-get-into-teaching-app-2533.london.cloudapps.digital/events/train-to-teach-manchester-event-040922/apply/completed)

### CODE REVIEW

**Review by peteryates — DISMISSED** [review]

**Comment by ethax-ross** [comment]
@gemmadallmandfe I've updated so the headings are now in correct order going from h1 -> h2, however we probably want too look at the headings on the website more widely as we're having to hack the CSS in this section to get them to match the design (the `h1` is styled as a `h2` and the `h2` tags are now styled as `h3` tags).

**Comment by gemmadallmandfe** [comment]
Thanks @ethax-ross 

The h3s in the signpost boxes should really be h2s though?
image

Re looking at the headings site-wide - I'll raise a separate ticket for @gazcarr to look at

**Review by peteryates — APPROVED** [review]
Looks good. The pages I checked look like they have the right structure.

The mailing list wizard's final page has an equally-sized main and subsequent heading

image

**Comment by gazcarr** [comment]
@ethax-ross 

Do we not just simply follow the GDS patterns for CSS naming on headings. Basically, we can have heading tags in the correct order in the markup but can easily style say a H1 to something small by using the class name?

`<h1 class="govuk-heading-l">govuk-heading-l</h1>
<h2 class="govuk-heading-m">govuk-heading-m</h2>
<h3 class="govuk-heading-s">govuk-heading-s</h3>`

**Pull request merged**
