### PR TITLE
Updating page titles and meta descriptions

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card

https://trello.com/c/Glai1fdb/4458-review-page-titles-and-meta-descriptions

### Context

We want to try and tweak some of our page titles and meta descriptions to better target keywords and boost organic search performance.

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Looks good to me - apart from maybe the qualifications heading change @EllieNodder 
image

**Review by philspray — APPROVED** [review]
Looks good to me

**Comment by EllieNodder** [comment]
> Looks good to me - apart from maybe the qualifications heading change @EllieNodder image

now that I think about it, really strange that the h1 and h2 are basically the same 🤔 will tweak

**Review by philspray — APPROVED** [review]
looks good to me

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
