### PR TITLE
Restyle the puple box, remove black on white text

### PR DESCRIPTION
**Pull request by peteryates**
### Trello card

https://trello.com/c/YxpCTLc7/2849-review-the-design-of-the-steps-block

### Context and changes

Also adjust the margins and spacing a little to make it a bit more visually appealing.

| Before | After |
| ------- | ------- |
| Screenshot from 2022-01-17 16-48-07 | Screenshot from 2022-01-17 16-48-14 |

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
@gazcarr One for you to look at!

I'm wondering if the h2 now gets a bit lost, especially on mobile. Does it need to be bigger? Different?

Also: Does this box it take up too much space on mobile now as well with extra spacing?

**Comment by peteryates** [comment]
@gemmadallmandfe - I tried to follow the spacing on the image, I think it's a might be a bit much too. Will reduce it a bit and re-push

**Comment by peteryates** [comment]
cc @gemmadallmandfe, @gazcarr 

https://user-images.githubusercontent.com/128088/149925930-3df76abb-0ef5-4e77-a70b-474bebee7885.mp4

**Review by gemmadallmandfe — APPROVED** [review]
Looks much better to me now @peteryates - happy for this to be merged when ready

**Pull request merged**
