### PR TITLE
adding ecf content

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card

https://trello.com/c/r9yhLQ0P/3203-promote-and-signpost-ecf-materials-on-rtt-webpage?filter=member:ellienodder

### Context

Added an ECF section to the page. Also changed some h4s to h3s, and added a question mark to 'why now'.

### CODE REVIEW

**Comment by EllieNodder** [comment]
@peteryates this hasn't worked :( could you take a look when you get a min pls?

**Review by peteryates — APPROVED** [review]
Looks good, so long as we're happy with the content changes @gemmadallmandfe, @valentine-carter

**Comment by gemmadallmandfe** [comment]
@peteryates @EllieNodder @valentine-carter 
I've added a couple of comments but generally looks good to me

Ideally we'd show this to the returners team before deploying, for sense-checking/involvement
As such, if it is easy to create as a new PR, I'd probably go for that option (with a view to then definitely getting this into production before the end of this week).

If that's a pain, I'm happy for this to be deployed and we can get them to review asap in prod

**Comment by gemmadallmandfe** [comment]
Closing this PR as @EllieNodder created https://github.com/DFE-Digital/get-into-teaching-app/pull/2540 instead, given that this one wouldn't build

**Pull request closed without merging**
