### PR TITLE
Overseas returner changes for teaching vacancies

### PR DESCRIPTION
**Pull request by caitlin-reidy**
### Trello card
https://trello.com/c/Q3tpbumH/5265-plan-move-of-return-to-england-from-overseas-content-to-teaching-vacancies#comment-65704bf3c5b897970709280f

### Context
We now want to move the content relating to domestic qualified teachers who have been working overseas and who are now looking to return to England to teach to Teaching Vacancies

### Changes proposed in this pull request

- delete blog 'returning to teaching with international experience'
- delete stories-kate.jpg
- delete return to england after teaching overseas and accordions and redirect to teaching vacancies 
- redirect primary returner to teaching vacancies 
- delete blog tag

### CODE REVIEW

**Comment by caitlin-reidy** [comment]
The redirects to the teacher vacancies aren't working yet, talking to Pete to figure out why so hopefully will be figured out soon!

**Comment by gemmadallmandfe** [comment]
> @gemmadallmandfe turns out the redirects wont work at the moment because they are to an external website. @martyn-w I spoke to pete and he's said the routes page needs a bit of code inputting that allows redirects to link to external websites because it won't at the moment. Are you able to help do this please?

@martyn-w @caitlin-reidy We implemented an external redirect previously - see https://github.com/DFE-Digital/get-into-teaching-app/pull/3465
Just need to replicate this with another URL!

**Comment by martyn-w** [comment]
To clarify, the issue is that navigating to 
`https://get-into-teaching-app-review-3743.test.teacherservices.cloud/non-uk-teachers/return-to-england-after-teaching-overseas/`
redirects to: 
`https://get-into-teaching-app-review-3743.test.teacherservices.cloud/https://teaching-vacancies.campaign.gov.uk/return-to-england-after-teaching-overseas/`
But it should redirect to:
`https://teaching-vacancies.campaign.gov.uk/return-to-england-after-teaching-overseas/`

**Comment by gemmadallmandfe** [comment]
@martyn-w @caitlin-reidy 

We are removing `/non-uk-teachers/return-to-england-after-teaching-overseas/` and need to redirect it to `https://teaching-vacancies.campaign.gov.uk/return-to-england-after-teaching-overseas/`

@martyn-w On a similar previous PR https://github.com/DFE-Digital/get-into-teaching-app/pull/3465, we did this in the routes file as below:
image

@caitlin-reidy Once Martyn has done this change in the routes file, all other pages (eg blogs) we are deleting can be redirected in the redirects config file to `/non-uk-teachers/return-to-england-after-teaching-overseas/`

**Comment by martyn-w** [comment]
Thanks @gemmadallmandfe  and @caitlin-reidy , I've pushed a small update which redirects:

```
/non-uk-teachers/return-to-england-after-teaching-overseas/ --> https://teaching-vacancies.campaign.gov.uk/return-to-england-after-teaching-overseas/
```

Once its deployed, please check that it is working correctly.

**Comment by gemmadallmandfe** [comment]
> Thanks @gemmadallmandfe and @caitlin-reidy , I've pushed a small update which redirects:
> 
> ```
> /non-uk-teachers/return-to-england-after-teaching-overseas/ --> https://teaching-vacancies.campaign.gov.uk/return-to-england-after-teaching-overseas/
> ```
> 
> Once its deployed, please check that it is working correctly.

Looks like it is working to me - thanks @martyn-w !

**Comment by martyn-w** [comment]
👍  LGTM

**Review by martyn-w — APPROVED** [review]

**Comment by gemmadallmandfe** [comment]
One of the external redirects is not working as expected:
`get "/explore-my-options/return-to-teaching/return-to-teaching-in-england-from-overseas", to: redirect("https://teaching-vacancies.campaign.gov.uk/return-to-england-after-teaching-overseas/")`

This is redirecting to `/train-to-be-a-teacher` instead

I think this is being overridden by "/explore-my-options(*option)": "/train-to-be-a-teacher"` in the redirects file

However, as this is a legacy redirect and will have next to no traffic, I am happy to approve this PR

I will raise a separate ticket for the backlog on clearing up our redirects file more generally and making sure we don't have conflicting redirects

cc @martyn-w for info

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
