### PR TITLE
Feature/footer social

### PR DESCRIPTION
**Pull request by sigmaben**
Add brand icons font variant. 
Add social links.
Update Footer styling to accommodate links and bring in line with design. 
Update talk section stylie to fix bugs from chat integration

### CODE REVIEW

**Review by jebw — COMMENTED** [review]
How necessary is it to implement this with flexbox? I'm aware IE11 doesn't support that very well and that's what most of DfE uses as a default browser?

**Comment by sigmaben** [comment]
@jebw Id prefer to use flexbox over table as a display property as it serves most users better. I'll add fallback support for IE11 and add to the PR.

**Review by jebw — DISMISSED** [review]
Looks good but can you add whitespace before the new attributes

**Review by jebw — APPROVED** [review]
LGTM

**Pull request merged**
