### PR TITLE
Hero redesign

### PR DESCRIPTION
**Pull request by peteryates**
### Trello card

https://trello.com/c/1kYBRmyZ/511-development-code-up-homepage-hero-section

### Context

The hero section of pages was due a redesign. The new version should hopefully bring a little more attention to the heading text which was sometimes lost in the image

### Changes proposed in this pull request

Redesign the hero and heading section of pages.

There are two new components, `Sections::HeaderComponent` and `Sections::HeroComponent`. They both render a `h1` with a responsive image, but the hero component will also add subtitles and they are significantly-different style-wise to warrant separate styles.

#### Hero

| Before | After |
| ------ | ------ |
| Screenshot from 2020-11-19 16-33-59 | Screenshot from 2020-11-19 16-33-56 |
| Screenshot from 2020-11-19 16-34-14 | Screenshot from 2020-11-19 16-34-12 |

#### Header (content)

| Before | After |
| ----- | ----- |
| Screenshot from 2020-11-20 14-48-44 | Screenshot from 2020-11-20 14-32-39 |
| Screenshot from 2020-11-20 14-33-18 | Screenshot from 2020-11-20 14-32-52 |

### CODE REVIEW

**Comment by peteryates** [comment]
Screenshot from 2020-11-23 09-40-05

Screenshot from 2020-11-23 09-48-56

Note that IE doesn't support setting both the style and thickness of underlines as multiple arguments to `text-decoration` so we're supplying both separately. Also, IE doesn't support `text-underline-offset` at all so it's a little closer to the text.

**Review by ethax-ross — APPROVED** [review]
Looks good, there's a couple of pages where viewing at a certain resolution (circa iPad Pro) doesn't work out well with how the image gets laid out, but its going to be tricky to cover all scenarios using this kind of layout I think.

Screenshot 2020-11-24 at 09 56 52
Screenshot 2020-11-24 at 09 57 11

**Comment by peteryates** [comment]
A bit of `transform: scaleX(-1);` solves everything 😂 

Screenshot from 2020-11-24 10-24-22

**Comment by sigmaben** [comment]
Based on the screenshot, just some alignment tweaks. For the home page, the sub heading should be aligned with the headline, as if the whole thing had been rotated together. 

For the sub page, the title should align to the logo text rather than being indented.

**Comment by peteryates** [comment]
@sigmaben I'll add another PR with those fixes

**Pull request merged**
