### PR TITLE
Change date formats on check answers page in adviser funnel

### PR DESCRIPTION
**Pull request by sarahcrack**
### Trello card

https://trello.com/c/Z6odPjEh/6961-change-date-formats-on-check-answers-page-in-adviser-funnel-on-git

### Context

Whilst reviewing the adviser funnel as part of the move to GIT, a few minor improvements were noticed. One of these concerns the date format used on the check answers page ([/teacher-training-adviser/sign_up/review_answers](https://getintoteaching.education.gov.uk/teacher-training-adviser/sign_up/review_answers)) for date of birth and for the callback bookings. The date format should be e.g. 1 January 1990.

### Changes proposed in this pull request

Minor tweak to `AnswerHelper` to format dates with `:govuk_zero_pad`

### Guidance to review

- check visuals meet GDS best practice on check answers page. 
- ensure this change only relates to the display on the review answers page; the format of the value passed to CRM should not be changed.

### CODE REVIEW

**Comment by sarahcrack** [comment]
N.B. need to check whether this change to the `AnswerHelper` affects the passing of date values to CRM.

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me from a front end perspective

Have asked @Sarah-DfE to review from style perspective and also needs confirmation from @martyn-w that this does not impact the values passed in the API

**Review by martyn-w — APPROVED** [review]
👍  LGTM

**Comment by Sarah-DfE** [comment]
Looks good to me too!

**Pull request merged**
