### PR TITLE
Create Inspiration Card Component

### PR DESCRIPTION
**Pull request by spencerldixon**
### Trello card

https://trello.com/c/QAALrbpf/6408-phase-3-build-inspiration-section-to-be-added-to-category-and-sub-category-pages?filter=member:spencerldixon

### Context

We want to distinguish inspirational from factual content on the GiT website

### Changes proposed in this pull request

- Create an inspiration card component with a pink theme
- Create a "Find out what teachers say" sections
- Removes background from category styling (currently this causes a white gap when using category cards on a coloured background)

### CODE REVIEW

**Comment by jenhadfield-dfe** [comment]
Looks really good!

**Comment by gemmadallmandfe** [comment]
@jenhadfield-dfe Are you happy with this (looks fine to me)?

If so @spencerldixon you will need to back out the changes to the Pay and benefits page on this PR so we are just merging the component itself and not applying it to any page yet (as these changes aren't the ones we want to do with this component!)

Once you've done that, can you get a tech review (if needed)? And Jen can approve from a design perspective

Also - should we add anything to the content.md guidance page re this new component? Can be done retrospectively if easier

**Review by jenhadfield-dfe — DISMISSED** [review]

**Review by martyn-w — COMMENTED** [review]
Looks great 👍 

could you add a spec to `spec/components/content` for the new inspiration card component?

**Review by martyn-w — APPROVED** [review]
👍 LGTM

**Pull request merged**
